---
title: "The Right Clubs"
type: "exercise"
description: "Using symbols, find the right golf clubs for you!"
tags: "arrays, symbols"
visibility: "public"
ignore:
- "solution.rb"
- "the_right_clubs.md"
